//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.21 at 12:30:56 PM GMT+01:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://localhost:8080/schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package localhost._8080.schema;
